### ISSUE TITLE
Chiseltest supports stdin at runtime?

### ISSUE THREAD

**Issue by B10615053** [ucb-bar/chiseltest#606]
I had a UART Module, and I had successfully tested it with normal `BasicTester` which gives the UART test data from test list serially.
`BasicTester` allows programmer to use `printf` to show test result, so I am wondering whether chiseltest also support method like `scanf` which can let programmer enter test data manually at runtime?

**Comment by ekiwi** [comment]
If you want to read stdin, I would recommend [using Scala to do so](https://stackoverflow.com/questions/4585655/how-to-read-from-standard-input-line-by-line) and then to communicate the data to your design under test using `poke` from a standard Chisel test, i.e., not using `BasicTester`, but the `test(new ....) { dut => dut.in.poke(...) }` functionality.

We are not going to add `scanf` to Chisel since Scala already has much better support for reading from a file or stdin.
