### ISSUE TITLE
The waveform doesn't reflect changes in the input port until io.clock.peek 

### ISSUE THREAD

**Issue by jerryhethatday** [ucb-bar/chiseltest#696]
I tried the chiseltest framework, and write a simple combinational module to test. The output should output the value in the same cycle of input. So, my assumption is that no io.clock.step() is needed. However, when I did not step the clock, the generated waveform will not reflect the input I drive into the DUT. Only if I step the clock, corresponding input will be drived and correct wavefrom is displayed. Also, the circuit seems working properly even when I did not step the clock(`println(c.io.output.tmp_normDist.peek().litValue.toString(16))` works as expected). 
Even in the generated waveform when I setp the clock, the input seems changes during the falling edge of the clock, which is also a bit wired. 
![image](https://github.com/ucb-bar/chiseltest/assets/1823246/e27e67f9-df7a-4811-85ae-21295751b692)
Can anyone tell me whether this is the expected thing or not? 
Thanks!

**Comment by ekiwi** [comment]
> The output should output the value in the same cycle of input. So, my assumption is that no io.clock.step() is needed. However, when I did not step the clock, the generated waveform will not reflect the input I drive into the DUT.

If you are changing an input without a `step`, only the final value before the step will be displayed in the waveform, I think.



> Also, the circuit seems working properly even when I did not step the clock(`println(c.io.output.tmp_normDist.peek().litValue.toString(16))` works as expected).

That is expected for a combinatorial circuit. Generally we like to encode the expected value like this:
```
c.io.output.tmp_normDist.expect(0x41200000)
```

Then the testbench is self checking. Waveform output is mostly for debugging, not for checking correctness.



> Even in the generated waveform when I setp the clock, the input seems changes during the falling edge of the clock, which is also a bit wired.

That is something that chiseltest has done since the beginning of time. Essentially inputs that you `poke` all change on the falling clock edge and registers are updated on the rising edge. The idea behind this is that you might want to distinguish between combinatorial and sequential logic. However, many people - including me - would prefer to just have everything happen on the rising edge. I would love to change that, but don't have the time right now.
